name: Build and Deploy Notebooks

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Pull container image
      run: docker pull ghcr.io/lisp-stat/cl-jupyter:latest
    
    - name: Execute notebooks
      run: |
        docker run --rm \
          --user root \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          ghcr.io/lisp-stat/cl-jupyter:latest \
          bash -c "
            # Install jupyter if not available
            pip install jupyter nbconvert
            
            # Execute all notebooks
            find . -name '*.ipynb' -not -path './.git/*' -exec jupyter execute {} \;
          "
    
    - name: Convert notebooks to HTML
      run: |
        docker run --rm \
          --user root \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          ghcr.io/lisp-stat/cl-jupyter:latest \
          bash -c "
            # Debug: Check current user and permissions
            whoami
            id
            ls -la
            
            # Remove any existing _site directory and recreate
            rm -rf _site
            mkdir -p _site
            chmod 755 _site
            
            # Convert notebooks to HTML
            find . -name '*.ipynb' -not -path './.git/*' -exec jupyter nbconvert --to html --output-dir=_site {} \;
            
            # Create index.html
            echo '<h1>IPS9 - Introduction to the Practice of Statistics</h1>' > _site/index.html
            echo '<p>Jupyter notebooks for statistics education using Common Lisp.</p>' >> _site/index.html
            echo '<ul>' >> _site/index.html
            find . -name '*.ipynb' -not -path './.git/*' | while read file; do
              basename_file=\$(basename \"\$file\" .ipynb)
              echo \"<li><a href='\${basename_file}.html'>\${basename_file}</a></li>\" >> _site/index.html
            done
            echo '</ul>' >> _site/index.html
            
            # Debug: Check what was created
            ls -la _site/
          "
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        force_orphan: true
